# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import record.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inode', models.TextField(unique=True)),
                ('url', models.TextField(unique=True)),
                ('filename', models.TextField()),
                ('server_path', models.TextField(unique=True)),
                ('size', models.IntegerField()),
                ('dotcms_updated', models.DateTimeField()),
                ('dotcms_author', models.TextField()),
                ('last_reuploaded', models.DateTimeField(default=None, null=True, verbose_name='Manually fixed')),
                ('original_file', models.FileField(blank=True, null=True, upload_to=record.models.upload_to)),
                ('reupload_author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmptyFile',
            fields=[
            ],
            options={
                'verbose_name': 'Empty File',
                'proxy': True,
                'verbose_name_plural': 'Empty Files',
            },
            bases=('record.record',),
        ),
        migrations.CreateModel(
            name='FixedFile',
            fields=[
            ],
            options={
                'verbose_name': 'Fixed file',
                'proxy': True,
                'verbose_name_plural': 'Fixed Files',
            },
            bases=('record.record',),
        ),
    ]
